### ISSUE TITLE
Python3 qtpy uses deprecated __version__ attribute from PySide

### ISSUE THREAD

**Issue by AndyMender** [spyder-ide/qtpy#116] opened 2017-05-11 05:03 UTC
I am running openSUSE Tumbleweed and I have the following problem:
```pytb
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/qtpy/__init__.py", line 119, in <module>
    from PySide import __version__ as PYSIDE_VERSION  # analysis:ignore
ImportError: cannot import name '__version__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/spyder3", line 3, in <module>
    start.main()
  File "/usr/lib/python3.6/site-packages/spyder/app/start.py", line 103, in main
    from spyder.app import mainwindow
  File "/usr/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 49, in <module>
    requirements.check_qt()
  File "/usr/lib/python3.6/site-packages/spyder/requirements.py", line 39, in check_qt
    import qtpy
  File "/usr/lib/python3.6/site-packages/qtpy/__init__.py", line 125, in <module>
    raise PythonQtError('No Qt bindings could be found')
qtpy.PythonQtError: No Qt bindings could be found
```
It seems `qtpy` tries to import `__version__`, which was only available in the Python2 version of `PySide`. I had a quick `dir(PySide)` look at the available attributes and there isn't one that handles a version string.

**Comment by ccordoba12** [comment] 2017-05-11 15:11
Ok, thanks for reporting. We'll fix this in qtpy 1.3.

**Comment by ccordoba12** [comment] 2017-05-11 15:52
@rlaverde, please investigate this one.

**Comment by ccordoba12** [comment] 2017-05-11 15:54
@AndyMender, by the way, Spyder **3+** doesn't work with Pyside anymore, sorry.

**Comment by AndyMender** [comment] 2017-05-11 18:50
@ccordoba12, I understand and that's fine with me, but what about the faulty import? :)

**Comment by ccordoba12** [comment] 2017-05-11 18:54
Sure, that's a bug.

**Comment by rlaverde** [comment] 2017-05-15 15:26
I'm not able to reproduce this bug, I created a conda enviroment with python3 and PySide,and `PySide.__version__` attribute exists

Idk if maybe It only happens with OpenSuse, how did you install it? pip, conda, zypper? maybe you are using an old version of pyside

**Comment by AndyMender** [comment] 2017-05-15 18:31
I installed Spyder3 and PySide from the openSUSE Tumbleweed repositories, making sure that both are compatible with Python3. I now tried to reproduce the error on a Debian "Stretch" (Testing) system and couldn't. As you mentioned, `PySide.__version__` exists. It must be something specific to openSUSE then. 

I filed a bug report in the SUSE bug tracker so hopefully the maintainer will resolve this.

**Comment by ccordoba12** [comment] 2017-05-15 20:08
> I filed a bug report in the SUSE bug tracker so hopefully the maintainer will resolve this.

Closing for now then.

**Closed by ccordoba12** 2017-05-15 20:08 UTC

**Comment by sebix** [comment] 2017-07-21 12:09
@AndyMender 
> I filed a bug report in the SUSE bug tracker so hopefully the maintainer will resolve this.

Do you have a link to the report?

**Comment by AndyMender** [comment] 2017-07-21 17:32
Apologies, I should've linked it here instantly: https://bugzilla.opensuse.org/show_bug.cgi?id=1038377
No development until now, unfortunately :(. Since I no longer have an openSUSE installation on any of my computers, I cannot tell whether the problem was fixed on their side.

**Comment by sebix** [comment] 2017-07-21 18:06
> I installed Spyder3 and PySide from the openSUSE Tumbleweed repositories, making sure that both are compatible with Python3. I now tried to reproduce the error on a Debian "Stretch" (Testing) system and couldn't. As you mentioned, PySide.__version__ exists. It must be something specific to openSUSE then.

Which version of PySide did you test? I have 1.2.4 from openSUSE TW, the `__version__` variable does not exist. However, the import of qtpy and spyder3 work fine.

**Comment by AndyMender** [comment] 2017-07-21 20:48
@sebix, I have since changed my main operating system many times and I don't remember anymore. Sorry!

**Comment by sebix** [comment] 2017-07-21 20:56
Ok, then I assumed it's fixed ("works for me").
