### ISSUE TITLE
Is there documents or tutorials for QtPy?

### ISSUE THREAD

**Issue by xingrui94** [spyder-ide/qtpy#231] opened 2021-02-20 06:39 UTC
Is there documents or tutorials for QtPy?

**Comment by dalthviz** [comment] 2021-11-04 17:17
Closing this as duplicate of https://github.com/spyder-ide/qtpy/issues/85 but hopefully for v2.0.0 some level of documentation will be available

**Closed by dalthviz** 2021-11-04 17:17 UTC
