### ISSUE TITLE
PySide6 bug

### ISSUE THREAD

**Issue by hannesdelbeke** [spyder-ide/qtpy#484] opened 2024-04-28 09:45 UTC
Hi

I founda bug, and believe it's related to PySide6.7 release.
starting an issue here to make others aware since I believe it might affect everyone using PyQt.
- bug report on PySide forum https://bugreports.qt.io/browse/PYSIDE-2674
- bug report on my app's repo https://github.com/plugget/plugget-unreal-plugin/issues/14

TLDR: using `from .. import *` and certain import orders break in Pyside6.7, and it seems qtpy triggers one of those conditions.

```python
from PySide6 import QtWidgets

app = QtWidgets.QApplication()
window = QtWidgets.QWidget()
layout = QtWidgets.QVBoxLayout()
window.setLayout(layout)
window.show()
app.exec_()
```
this code throws an error
```
LogPython: Error: Traceback (most recent call last):
LogPython: Error:   File "<string>", line 1, in <module>
LogPython: Error:   File "D:\Program Files\Epic Games\UE_5.4\Engine\Binaries\ThirdParty\Python3\Win64\Lib\site-packages\plugget_qt\__init__.py", line 20, in test
LogPython: Error:     window.setLayout(layout)
LogPython: Error: TypeError: 'PySide6.QtWidgets.QWidget.setLayout' called with wrong argument types:
LogPython: Error:   PySide6.QtWidgets.QWidget.setLayout(QVBoxLayout)
LogPython: Error: Supported signatures:
LogPython: Error:   PySide6.QtWidgets.QWidget.setLayout(PySide6.QtWidgets.QLayout)
```

**Comment by hannesdelbeke** [comment] 2024-04-28 09:55
for now, to get around this, i replaced this line
```python
import qtpy.QtWidgets as QtWidgets
```
with 
```python
try:
    import PySide6.QtWidgets as QtWidgets
except ImportError:
    import qtpy.QtWidgets as QtWidgets
```

**Comment by ccordoba12** [comment] 2024-04-28 15:51
Hey @hannesdelbeke, thanks for reporting. This is basically a duplicate of issue #480 and it's not our fault.

It seems PySide 6.7 broke star imports, which is what we use all over the place in this library (instead of importing object by object).

**Closed by ccordoba12** 2024-04-28 15:51 UTC
