### ISSUE TITLE
Add official support for Python 3.11

### ISSUE THREAD

**Issue by florisla** [spyder-ide/qtpy#386] opened 2022-11-09 09:11 UTC
Hi,

The recent PySide6 release 6.4.0.1 now supports Python 3.11 too.

Qtpy officially only supports 3.6 to 3.10 but not yet 3.11.

Here's the commit which added 3.10: https://github.com/spyder-ide/qtpy/commit/005641217fbece5e2844ffb844596c90ae3850b6 .

Thanks a lot for this amazing project!

**Comment by dalthviz** [comment] 2022-11-09 18:17
Hi @florisla thank you for the feedback and your nice words! We will do this in a future release :+1:

**Comment by CAM-Gerlach** [comment] 2022-12-17 10:19
FYI, I've opened PR #392 to implement this.

**Comment by CAM-Gerlach** [comment] 2022-12-18 22:52
@dalthviz Since this is only a CI/tests/metadata update, and the existing code in 2.3 is already 3.11-compatible with no changes, can we bump this to 2.3.1 so it can be merged more promptly? Otherwise, there could be regressions in 3.11 support or conflicts with the PR, and this allows us to benefit from the updates to our CIs (which is basically all the changes) right away.

**Closed** 2022-12-19 18:02 UTC
Labels: type:Task
