### ISSUE TITLE
Problems with pyside6 6.4.2

### ISSUE THREAD

**Issue by duolabmeng6** [spyder-ide/qtpy#409] opened 2023-02-28 22:58 UTC
i use `import qtawesome` Problems encountered

My version pyside6 6.4.2

error
```
Traceback (most recent call last):
  File "C:\pyefun\QtEsayDesigner\组件的学习\7.浏览器\窗口_托盘菜单.py", line 6, in <module>
    from qtefun.图标 import 获取图标
  File "C:\pyefun\QtEsayDesigner\qtefun\图标.py", line 5, in <module>
    import qtawesome
  File "C:\Users\csuil\.virtualenvs\QtEsayDesigner\lib\site-packages\qtawesome\__init__.py", line 23, in <module>
    from qtpy import QtCore, QtWidgets, QtGui
  File "C:\Users\csuil\.virtualenvs\QtEsayDesigner\lib\site-packages\qtpy\QtCore.py", line 90, in <module>
    Qt.MidButton = Qt.MouseButton.MiddleButton = Qt.MiddleButton
  File "C:\Python39\lib\enum.py", line 472, in __setattr__
    raise AttributeError('Cannot reassign members.')
AttributeError: Cannot reassign members.

```

**Comment by CAM-Gerlach** [comment] 2023-03-01 01:11
Hi, this appears to be a duplicate of #373 which was fixed in QtPy 2.3.0 , released Nov 7, 2022. While you haven't specified your QtPy version, based on the line number and the code on that line, you're apparently using QtPy 2.1.0 (released 10 months ago on May 2, 2022), which does not contain the fix and was released long before that version of PySide6 (released a little over a month ago in Jan 2023). Therefore, please upgrade to the current, supported version of QtPy (2.3.0) to resolve your issue. Thanks!

**Closed by CAM-Gerlach** 2023-03-01 01:11 UTC
Labels: reso:duplicate
