### ISSUE TITLE
One test fails on FreeBSD

### ISSUE THREAD

**Issue by yurivict** [spyder-ide/qtpy#371] opened 2022-10-08 03:50 UTC
```
========================================================================================== FAILURES ==========================================================================================
__________________________________________________________________________________ test_qfontmetrics_width ___________________________________________________________________________________

qtbot = <pytestqt.qtbot.QtBot object at 0x93a1dc820>

    @pytest.mark.skipif(
        sys.platform.startswith('linux') and not_using_conda(),
        reason="Fatal Python error: Aborted on Linux CI when not using conda")
    def test_qfontmetrics_width(qtbot):
        """Test QFontMetrics and QFontMetricsF width"""
        assert QtGui.QFontMetrics.width is not None
        assert QtGui.QFontMetricsF.width is not None
        font = QtGui.QFont("times", 24)
        font_metrics = QtGui.QFontMetrics(font)
        font_metricsF = QtGui.QFontMetricsF(font)
        width = font_metrics.width("Test")
        widthF = font_metricsF.width("Test")
>       assert width in range(40, 62)
E       assert 67 in range(40, 62)
E        +  where range(40, 62) = range(40, 62)

qtpy/tests/test_qtgui.py:23: AssertionError
```

Version 2.2.1
Python 3.9
FreeBSD 13.1 STABLE

**Comment by ccordoba12** [comment] 2022-10-08 11:32
The test is marked as not working on Linux, as you can see on the top of it. Since we don't support FreeBSD, but they are are similar operating systems, it should skipped there too.

**Closed by ccordoba12** 2022-10-08 11:32 UTC

**Comment by CAM-Gerlach** [comment] 2022-10-12 07:02
@yurivict if you could report what `sys.platform` prints on your machine, we could maybe add a skip for it (or just `or "bsd" in sys.platform`).

**Comment by yurivict** [comment] 2022-10-12 07:04
```freebsd13```
You can skip strings beginning with ```freebsd```.

**Comment by CAM-Gerlach** [comment] 2022-10-12 07:08
@ccordoba12 Any objection to @yurivict submitting a small PR to add a single skip for `freebsd` (or `bsd` generally)? Only one test failed on that platform, and it is unlikely that one skip buried deep in the test suite will confuse people into thinking we support BSD, so seems harmless to me.

**Comment by ccordoba12** [comment] 2022-10-12 15:16
> Any objection to @yurivict submitting a small PR to add a single skip for freebsd (or bsd generally)?

The problem is that we'll give the impression that we support FreeBSD when in reality we don't.

So if @yurivict is trying to package Qtpy for FreeBSD, I think the simplest thing to do is to `sed` all `linux` strings around and replace them with `freebsd`. That's what I've seen other FreeBSD maintainers do.

**Comment by CAM-Gerlach** [comment] 2022-10-12 18:51
Right, though as mentioned, I'm not sure a single string inside a skip decorator buried in the test suite will give that impression if we clearly state somewhere people are much more likely to see, like the Readme, that we don't. Though, if it is more easily solved with tooling on their end, then I suppose it is moot.

**Comment by CAM-Gerlach** [comment] 2022-10-12 18:52
Also, changed the close status to better reflect the current state of the issue, unless @ccordoba12 / @dalthviz agree with adding a skip.
