### ISSUE TITLE
Take out certain hours from analysis

### ISSUE THREAD

**Issue by ziqbal99** [spyder-ide/qtpy#436] opened 2023-06-28 15:24 UTC
### Discussed in https://github.com/spyder-ide/qtpy/discussions/435

<div type='discussions-op-text'>

<sup>Originally posted by **ziqbal99** June 28, 2023</sup>
 -how to write a code to eliminate certain hours of data from analysis like I am running a report from 6am to 5pm. How can I skip 7-9 am data from report. Can someone provide example of python code?</div>
can some also provide codes to skip weekend data from analysis?

**Comment by ccordoba12** [comment] 2023-06-28 18:01
Closing as a duplicate of #435.

**Closed by ccordoba12** 2023-06-28 18:01 UTC
